<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\dist\assets\img\AdminLTEFullLogo.png" />
    <Content Remove="wwwroot\dist\assets\img\AdminLTELogo.png" />
    <Content Remove="wwwroot\dist\assets\img\avatar.png" />
    <Content Remove="wwwroot\dist\assets\img\avatar2.png" />
    <Content Remove="wwwroot\dist\assets\img\avatar3.png" />
    <Content Remove="wwwroot\dist\assets\img\avatar4.png" />
    <Content Remove="wwwroot\dist\assets\img\avatar5.png" />
    <Content Remove="wwwroot\dist\assets\img\boxed-bg.jpg" />
    <Content Remove="wwwroot\dist\assets\img\boxed-bg.png" />
    <Content Remove="wwwroot\dist\assets\img\credit\american-express.png" />
    <Content Remove="wwwroot\dist\assets\img\credit\cirrus.png" />
    <Content Remove="wwwroot\dist\assets\img\credit\mastercard.png" />
    <Content Remove="wwwroot\dist\assets\img\credit\paypal.png" />
    <Content Remove="wwwroot\dist\assets\img\credit\paypal2.png" />
    <Content Remove="wwwroot\dist\assets\img\credit\visa.png" />
    <Content Remove="wwwroot\dist\assets\img\default-150x150.png" />
    <Content Remove="wwwroot\dist\assets\img\icons.png" />
    <Content Remove="wwwroot\dist\assets\img\photo1.png" />
    <Content Remove="wwwroot\dist\assets\img\photo2.png" />
    <Content Remove="wwwroot\dist\assets\img\photo3.jpg" />
    <Content Remove="wwwroot\dist\assets\img\photo4.jpg" />
    <Content Remove="wwwroot\dist\assets\img\prod-1.jpg" />
    <Content Remove="wwwroot\dist\assets\img\prod-2.jpg" />
    <Content Remove="wwwroot\dist\assets\img\prod-3.jpg" />
    <Content Remove="wwwroot\dist\assets\img\prod-4.jpg" />
    <Content Remove="wwwroot\dist\assets\img\prod-5.jpg" />
    <Content Remove="wwwroot\dist\assets\img\user1-128x128.jpg" />
    <Content Remove="wwwroot\dist\assets\img\user2-160x160.jpg" />
    <Content Remove="wwwroot\dist\assets\img\user3-128x128.jpg" />
    <Content Remove="wwwroot\dist\assets\img\user4-128x128.jpg" />
    <Content Remove="wwwroot\dist\assets\img\user5-128x128.jpg" />
    <Content Remove="wwwroot\dist\assets\img\user6-128x128.jpg" />
    <Content Remove="wwwroot\dist\assets\img\user7-128x128.jpg" />
    <Content Remove="wwwroot\dist\assets\img\user8-128x128.jpg" />
    <Content Remove="wwwroot\dist\css\adminlte.css" />
    <Content Remove="wwwroot\dist\css\adminlte.css.map" />
    <Content Remove="wwwroot\dist\css\adminlte.min.css" />
    <Content Remove="wwwroot\dist\css\adminlte.min.css.map" />
    <Content Remove="wwwroot\dist\css\adminlte.rtl.css" />
    <Content Remove="wwwroot\dist\css\adminlte.rtl.css.map" />
    <Content Remove="wwwroot\dist\css\adminlte.rtl.min.css" />
    <Content Remove="wwwroot\dist\css\adminlte.rtl.min.css.map" />
    <Content Remove="wwwroot\dist\docs\browser-support.html" />
    <Content Remove="wwwroot\dist\docs\color-mode.html" />
    <Content Remove="wwwroot\dist\docs\components\main-header.html" />
    <Content Remove="wwwroot\dist\docs\components\main-sidebar.html" />
    <Content Remove="wwwroot\dist\docs\customization.html" />
    <Content Remove="wwwroot\dist\docs\deployment.html" />
    <Content Remove="wwwroot\dist\docs\faq.html" />
    <Content Remove="wwwroot\dist\docs\getting-started.html" />
    <Content Remove="wwwroot\dist\docs\how-to-contribute.html" />
    <Content Remove="wwwroot\dist\docs\index.html" />
    <Content Remove="wwwroot\dist\docs\integrations.html" />
    <Content Remove="wwwroot\dist\docs\introduction.html" />
    <Content Remove="wwwroot\dist\docs\javascript\accessibility.html" />
    <Content Remove="wwwroot\dist\docs\javascript\card-widget.html" />
    <Content Remove="wwwroot\dist\docs\javascript\direct-chat.html" />
    <Content Remove="wwwroot\dist\docs\javascript\fullscreen.html" />
    <Content Remove="wwwroot\dist\docs\javascript\layout.html" />
    <Content Remove="wwwroot\dist\docs\javascript\plugins-overview.html" />
    <Content Remove="wwwroot\dist\docs\javascript\pushmenu.html" />
    <Content Remove="wwwroot\dist\docs\javascript\treeview.html" />
    <Content Remove="wwwroot\dist\docs\layout-blueprint.html" />
    <Content Remove="wwwroot\dist\docs\layout.html" />
    <Content Remove="wwwroot\dist\docs\license.html" />
    <Content Remove="wwwroot\dist\docs\migration.html" />
    <Content Remove="wwwroot\dist\docs\recipes.html" />
    <Content Remove="wwwroot\dist\docs\rtl.html" />
    <Content Remove="wwwroot\dist\examples\lockscreen.html" />
    <Content Remove="wwwroot\dist\examples\login-v2.html" />
    <Content Remove="wwwroot\dist\examples\login.html" />
    <Content Remove="wwwroot\dist\examples\register-v2.html" />
    <Content Remove="wwwroot\dist\examples\register.html" />
    <Content Remove="wwwroot\dist\forms\elements.html" />
    <Content Remove="wwwroot\dist\forms\layout.html" />
    <Content Remove="wwwroot\dist\forms\validation.html" />
    <Content Remove="wwwroot\dist\forms\wizard.html" />
    <Content Remove="wwwroot\dist\generate\theme.html" />
    <Content Remove="wwwroot\dist\index.html" />
    <Content Remove="wwwroot\dist\index2.html" />
    <Content Remove="wwwroot\dist\index3.html" />
    <Content Remove="wwwroot\dist\js\adminlte.js" />
    <Content Remove="wwwroot\dist\js\adminlte.js.map" />
    <Content Remove="wwwroot\dist\js\adminlte.min.js" />
    <Content Remove="wwwroot\dist\js\adminlte.min.js.map" />
    <Content Remove="wwwroot\dist\layout\collapsed-sidebar-without-hover.html" />
    <Content Remove="wwwroot\dist\layout\collapsed-sidebar.html" />
    <Content Remove="wwwroot\dist\layout\fixed-complete.html" />
    <Content Remove="wwwroot\dist\layout\fixed-footer.html" />
    <Content Remove="wwwroot\dist\layout\fixed-header.html" />
    <Content Remove="wwwroot\dist\layout\fixed-sidebar.html" />
    <Content Remove="wwwroot\dist\layout\layout-custom-area.html" />
    <Content Remove="wwwroot\dist\layout\layout-rtl.html" />
    <Content Remove="wwwroot\dist\layout\logo-switch.html" />
    <Content Remove="wwwroot\dist\layout\sidebar-mini.html" />
    <Content Remove="wwwroot\dist\layout\unfixed-sidebar.html" />
    <Content Remove="wwwroot\dist\mailbox\compose.html" />
    <Content Remove="wwwroot\dist\mailbox\inbox.html" />
    <Content Remove="wwwroot\dist\mailbox\read.html" />
    <Content Remove="wwwroot\dist\pages\404.html" />
    <Content Remove="wwwroot\dist\pages\500.html" />
    <Content Remove="wwwroot\dist\pages\calendar.html" />
    <Content Remove="wwwroot\dist\pages\chat.html" />
    <Content Remove="wwwroot\dist\pages\faq.html" />
    <Content Remove="wwwroot\dist\pages\file-manager.html" />
    <Content Remove="wwwroot\dist\pages\invoice.html" />
    <Content Remove="wwwroot\dist\pages\kanban.html" />
    <Content Remove="wwwroot\dist\pages\maintenance.html" />
    <Content Remove="wwwroot\dist\pages\pricing.html" />
    <Content Remove="wwwroot\dist\pages\profile.html" />
    <Content Remove="wwwroot\dist\pages\projects.html" />
    <Content Remove="wwwroot\dist\pages\settings.html" />
    <Content Remove="wwwroot\dist\tables\data.html" />
    <Content Remove="wwwroot\dist\tables\simple.html" />
    <Content Remove="wwwroot\dist\UI\general.html" />
    <Content Remove="wwwroot\dist\UI\icons.html" />
    <Content Remove="wwwroot\dist\UI\timeline.html" />
    <Content Remove="wwwroot\dist\widgets\cards.html" />
    <Content Remove="wwwroot\dist\widgets\info-box.html" />
    <Content Remove="wwwroot\dist\widgets\small-box.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ApiControllers\" />
    <Folder Include="Helpers\" />
    <Folder Include="ViewModels\" />
    <Folder Include="Services\" />
    <Folder Include="Repositories\" />
    <Folder Include="Views\Complaints\" />
    <Folder Include="Views\Maintenance\" />
    <Folder Include="Views\Visitors\" />
    <Folder Include="Views\Notices\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\dist\assets\img\AdminLTEFullLogo.png" />
    <None Include="wwwroot\dist\assets\img\AdminLTELogo.png" />
    <None Include="wwwroot\dist\assets\img\avatar.png" />
    <None Include="wwwroot\dist\assets\img\avatar2.png" />
    <None Include="wwwroot\dist\assets\img\avatar3.png" />
    <None Include="wwwroot\dist\assets\img\avatar4.png" />
    <None Include="wwwroot\dist\assets\img\avatar5.png" />
    <None Include="wwwroot\dist\assets\img\boxed-bg.jpg" />
    <None Include="wwwroot\dist\assets\img\boxed-bg.png" />
    <None Include="wwwroot\dist\assets\img\credit\american-express.png" />
    <None Include="wwwroot\dist\assets\img\credit\cirrus.png" />
    <None Include="wwwroot\dist\assets\img\credit\mastercard.png" />
    <None Include="wwwroot\dist\assets\img\credit\paypal.png" />
    <None Include="wwwroot\dist\assets\img\credit\paypal2.png" />
    <None Include="wwwroot\dist\assets\img\credit\visa.png" />
    <None Include="wwwroot\dist\assets\img\default-150x150.png" />
    <None Include="wwwroot\dist\assets\img\icons.png" />
    <None Include="wwwroot\dist\assets\img\photo1.png" />
    <None Include="wwwroot\dist\assets\img\photo2.png" />
    <None Include="wwwroot\dist\assets\img\photo3.jpg" />
    <None Include="wwwroot\dist\assets\img\photo4.jpg" />
    <None Include="wwwroot\dist\assets\img\prod-1.jpg" />
    <None Include="wwwroot\dist\assets\img\prod-2.jpg" />
    <None Include="wwwroot\dist\assets\img\prod-3.jpg" />
    <None Include="wwwroot\dist\assets\img\prod-4.jpg" />
    <None Include="wwwroot\dist\assets\img\prod-5.jpg" />
    <None Include="wwwroot\dist\assets\img\user1-128x128.jpg" />
    <None Include="wwwroot\dist\assets\img\user2-160x160.jpg" />
    <None Include="wwwroot\dist\assets\img\user3-128x128.jpg" />
    <None Include="wwwroot\dist\assets\img\user4-128x128.jpg" />
    <None Include="wwwroot\dist\assets\img\user5-128x128.jpg" />
    <None Include="wwwroot\dist\assets\img\user6-128x128.jpg" />
    <None Include="wwwroot\dist\assets\img\user7-128x128.jpg" />
    <None Include="wwwroot\dist\assets\img\user8-128x128.jpg" />
    <None Include="wwwroot\dist\css\adminlte.css" />
    <None Include="wwwroot\dist\css\adminlte.css.map" />
    <None Include="wwwroot\dist\css\adminlte.min.css" />
    <None Include="wwwroot\dist\css\adminlte.min.css.map" />
    <None Include="wwwroot\dist\css\adminlte.rtl.css" />
    <None Include="wwwroot\dist\css\adminlte.rtl.css.map" />
    <None Include="wwwroot\dist\css\adminlte.rtl.min.css" />
    <None Include="wwwroot\dist\css\adminlte.rtl.min.css.map" />
    <None Include="wwwroot\dist\docs\browser-support.html" />
    <None Include="wwwroot\dist\docs\color-mode.html" />
    <None Include="wwwroot\dist\docs\components\main-header.html" />
    <None Include="wwwroot\dist\docs\components\main-sidebar.html" />
    <None Include="wwwroot\dist\docs\customization.html" />
    <None Include="wwwroot\dist\docs\deployment.html" />
    <None Include="wwwroot\dist\docs\faq.html" />
    <None Include="wwwroot\dist\docs\getting-started.html" />
    <None Include="wwwroot\dist\docs\how-to-contribute.html" />
    <None Include="wwwroot\dist\docs\index.html" />
    <None Include="wwwroot\dist\docs\integrations.html" />
    <None Include="wwwroot\dist\docs\introduction.html" />
    <None Include="wwwroot\dist\docs\javascript\accessibility.html" />
    <None Include="wwwroot\dist\docs\javascript\card-widget.html" />
    <None Include="wwwroot\dist\docs\javascript\direct-chat.html" />
    <None Include="wwwroot\dist\docs\javascript\fullscreen.html" />
    <None Include="wwwroot\dist\docs\javascript\layout.html" />
    <None Include="wwwroot\dist\docs\javascript\plugins-overview.html" />
    <None Include="wwwroot\dist\docs\javascript\pushmenu.html" />
    <None Include="wwwroot\dist\docs\javascript\treeview.html" />
    <None Include="wwwroot\dist\docs\layout-blueprint.html" />
    <None Include="wwwroot\dist\docs\layout.html" />
    <None Include="wwwroot\dist\docs\license.html" />
    <None Include="wwwroot\dist\docs\migration.html" />
    <None Include="wwwroot\dist\docs\recipes.html" />
    <None Include="wwwroot\dist\docs\rtl.html" />
    <None Include="wwwroot\dist\examples\lockscreen.html" />
    <None Include="wwwroot\dist\examples\login-v2.html" />
    <None Include="wwwroot\dist\examples\login.html" />
    <None Include="wwwroot\dist\examples\register-v2.html" />
    <None Include="wwwroot\dist\examples\register.html" />
    <None Include="wwwroot\dist\forms\elements.html" />
    <None Include="wwwroot\dist\forms\layout.html" />
    <None Include="wwwroot\dist\forms\validation.html" />
    <None Include="wwwroot\dist\forms\wizard.html" />
    <None Include="wwwroot\dist\generate\theme.html" />
    <None Include="wwwroot\dist\index.html" />
    <None Include="wwwroot\dist\index2.html" />
    <None Include="wwwroot\dist\index3.html" />
    <None Include="wwwroot\dist\js\adminlte.js" />
    <None Include="wwwroot\dist\js\adminlte.js.map" />
    <None Include="wwwroot\dist\js\adminlte.min.js" />
    <None Include="wwwroot\dist\js\adminlte.min.js.map" />
    <None Include="wwwroot\dist\layout\collapsed-sidebar-without-hover.html" />
    <None Include="wwwroot\dist\layout\collapsed-sidebar.html" />
    <None Include="wwwroot\dist\layout\fixed-complete.html" />
    <None Include="wwwroot\dist\layout\fixed-footer.html" />
    <None Include="wwwroot\dist\layout\fixed-header.html" />
    <None Include="wwwroot\dist\layout\fixed-sidebar.html" />
    <None Include="wwwroot\dist\layout\layout-custom-area.html" />
    <None Include="wwwroot\dist\layout\layout-rtl.html" />
    <None Include="wwwroot\dist\layout\logo-switch.html" />
    <None Include="wwwroot\dist\layout\sidebar-mini.html" />
    <None Include="wwwroot\dist\layout\unfixed-sidebar.html" />
    <None Include="wwwroot\dist\mailbox\compose.html" />
    <None Include="wwwroot\dist\mailbox\inbox.html" />
    <None Include="wwwroot\dist\mailbox\read.html" />
    <None Include="wwwroot\dist\pages\404.html" />
    <None Include="wwwroot\dist\pages\500.html" />
    <None Include="wwwroot\dist\pages\calendar.html" />
    <None Include="wwwroot\dist\pages\chat.html" />
    <None Include="wwwroot\dist\pages\faq.html" />
    <None Include="wwwroot\dist\pages\file-manager.html" />
    <None Include="wwwroot\dist\pages\invoice.html" />
    <None Include="wwwroot\dist\pages\kanban.html" />
    <None Include="wwwroot\dist\pages\maintenance.html" />
    <None Include="wwwroot\dist\pages\pricing.html" />
    <None Include="wwwroot\dist\pages\profile.html" />
    <None Include="wwwroot\dist\pages\projects.html" />
    <None Include="wwwroot\dist\pages\settings.html" />
    <None Include="wwwroot\dist\tables\data.html" />
    <None Include="wwwroot\dist\tables\simple.html" />
    <None Include="wwwroot\dist\UI\general.html" />
    <None Include="wwwroot\dist\UI\icons.html" />
    <None Include="wwwroot\dist\UI\timeline.html" />
    <None Include="wwwroot\dist\widgets\cards.html" />
    <None Include="wwwroot\dist\widgets\info-box.html" />
    <None Include="wwwroot\dist\widgets\small-box.html" />
  </ItemGroup>

</Project>
